# Generated by Django 3.0.4 on 2020-04-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200401_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='image',
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, default='images/default_album.png', upload_to=''),
        ),
    ]
